backend:
  name: git-gateway
  branch: main
local_backend:
  url: http://localhost:8081/api/v1
  allowed_hosts: ["192.168.0.1"]
publish_mode: editorial_workflow
media_folder: "content/uploads"
collections:
  - name: "landing"
    label: "Strona startowa"
    folder: "cms/pages"
    create: false
    slug: "landing_page"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
