backend:
  name: git-gateway
  branch: main
local_backend:
  url: "http://localhost:8081/api/v1"
  allowed_hosts:
    - 192.168.0.1
publish_mode: editorial_workflow
media_folder: public/media
public_folder: media
collections:
  - label: Pages
    name: pages
    files:
      - name: landing
        label: Strona startowa
        file: cms/pages/landing_page.md
        fields:
          - label: Menu
            name: menu
            widget: object
            collapsed: false
            fields:
              - label: Kontakt
                name: contact
                widget: object
                summary: "{{ fields.label }}"
                fields:
                  - label: Element
                    name: label
                    widget: string
                  - label: Slug
                    name: slug
                    widget: string
              - label: O nas
                name: about
                widget: object
                summary: "{{ fields.label }}"
                fields:
                  - label: Element
                    name: label
                    widget: string
                  - label: Slug
                    name: slug
                    widget: string
              - label: Oferta
                name: offer
                widget: object
                summary: "{{ fields.label }}"
                fields:
                  - label: Element
                    name: label
                    widget: string
                  - label: Slug
                    name: slug
                    widget: string
          - label: Kolejność menu
            name: menuOrder
            widget: list
            fields:
              - label: Element
                name: value
                widget: string
          - label: Nazwa strony
            name: title
            widget: string
          - label: Logo
            name: logoImage
            widget: image
          - label: Główne powitanie
            name: mainWelcome
            widget: object
            fields:
              - label: Nagłówek 1
                name: header1
                widget: string
              - label: Nagłówek 2
                name: header2
                widget: string
              - label: Główny obrazek
                name: heroImage
                widget: image
          # - label: Zaproszenie do współpracy
          #   name: actionContent
          #   widget: object
          #   fields:
          #     - label: Główne pytanie
          #       name: question
          #       widget: string
          #     - label: Zaproszenie
          #       name: subQuestion
          #       widget: string
          #     - label: Podsumowanie
          #       name: summary
          #       widget: string
          - label: Opis
            name: description
            widget: text
          - label: Nagłówek informacji kontaktowych
            widget: string
            name: contactLabel
          - label: Adres
            name: address
            widget: object
            fields:
              - label: Linia Pierwsza
                name: line1
                widget: string
              - label: Linia Druga
                name: line2
                widget: string
          - label: Telefony
            name: phones
            widget: list
            fields:
              - label: Linia z telefonem
                name: label
                widget: string
              - label: Sam numer
                name: phone
                widget: string
              - label: "Typ telefonu"
                name: "type"
                widget: "select"
                options:
                  - { label: "Stacjonarny", value: "land" }
                  - { label: "Komórkowy", value: "cell" }
      - name: offers
        label: Oferta
        file: cms/pages/offers.md
        fields:
          - label: Wstęp
            name: description
            widget: text
          - label: Usługi
            name: offers
            widget: list
            fields:
              - label: Usługa
                name: description
                widget: text
              - label: Wyróżnienie
                name: emphasis
                widget: boolean
                required: false
